openapi: 3.0.3
info:
  title: MassMailer Campaign API
  version: 1.0.0
  description: |
    API для управления кампаниями массовых рассылок.
    В данный момент описан эндпоинт создания кампании и набор готовых примеров,
    которые можно использовать для быстрого заполнения формы в Swagger UI.
servers:
  - url: http://localhost:8080
    description: Локальный сервер кампаний
paths:
  /healthz:
    get:
      summary: Проверка состояния сервиса
      responses:
        '200':
          description: Сервис работает
          content:
            text/plain:
              schema:
                type: string
              example: ok
  /campaigns:
    get:
      summary: Список кампаний
      description: Возвращает постраничный список кампаний с агрегированной статистикой.
      operationId: listCampaigns
      tags:
        - Campaigns
      parameters:
        - in: query
          name: limit
          schema:
            type: integer
            format: int32
            minimum: 1
            maximum: 100
            default: 20
          description: Количество кампаний в выборке.
        - in: query
          name: offset
          schema:
            type: integer
            format: int32
            minimum: 0
            default: 0
          description: Смещение от начала выборки.
      responses:
        '200':
          description: Успешный ответ со списком кампаний.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CampaignListItem'
              examples:
                default:
                  value:
                    - id: 1
                      name: Weekly Newsletter #42
                      scheduled_at: 2024-04-20T10:00:00Z
                      status: queued
                      created_at: 2024-04-10T09:30:00Z
                      stats:
                        total: 3
                        pending: 1
                        sent: 1
                        failed: 1
                    - id: 2
                      name: New Feature Launch
                      scheduled_at: 2024-05-01T08:30:00Z
                      status: sending
                      created_at: 2024-04-18T12:00:00Z
                      stats:
                        total: 5
                        pending: 3
                        sent: 2
                        failed: 0
        '500':
          description: Внутренняя ошибка сервера при получении списка.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    post:
      summary: Создание кампании рассылки
      description: |
        Создает новую кампанию и планирует рассылку сообщений для каждого адресата.
      operationId: createCampaign
      tags:
        - Campaigns
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateCampaignRequest'
            examples:
              weeklyNewsletter:
                $ref: '#/components/examples/WeeklyNewsletter'
              productLaunch:
                $ref: '#/components/examples/ProductLaunch'
              reactivation:
                $ref: '#/components/examples/Reactivation'
      responses:
        '200':
          description: Кампания успешно создана
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateCampaignResponse'
              examples:
                default:
                  value:
                    id: 123
        '400':
          description: Ошибка валидации входных данных
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: "Key: 'CreateCampaignReq.Name' Error:Field validation for 'Name' failed on the 'required' tag"
        '502':
          description: Очередь задач недоступна
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: queue unavailable
        '500':
          description: Внутренняя ошибка сервера
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /campaigns/{id}:
    get:
      summary: Подробности кампании
      description: Возвращает полную информацию по кампании и статистику доставки.
      operationId: getCampaign
      tags:
        - Campaigns
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            format: int64
            minimum: 1
          description: Уникальный идентификатор кампании.
      responses:
        '200':
          description: Детали кампании.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampaignDetails'
              examples:
                default:
                  value:
                    id: 42
                    name: Weekly Newsletter #42
                    body: "<h1>Новости недели</h1><p>Привет!</p>"
                    scheduled_at: 2024-04-20T10:00:00Z
                    status: queued
                    created_at: 2024-04-10T09:30:00Z
                    stats:
                      total: 3
                      pending: 1
                      sent: 1
                      failed: 1
        '400':
          description: Некорректный идентификатор кампании.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: invalid id
        '404':
          description: Кампания не найдена.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: campaign not found
        '500':
          description: Внутренняя ошибка сервера при получении данных.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  schemas:
    CreateCampaignRequest:
      type: object
      required:
        - name
        - body
        - scheduled_at
        - recipients
      properties:
        name:
          type: string
          description: Человекочитаемое название кампании.
          example: "Weekly Newsletter #42"
        body:
          type: string
          description: HTML или текст шаблона письма.
          example: "<h1>Новости недели</h1><p>Привет, {{name}}!</p>"
        scheduled_at:
          type: string
          format: date-time
          description: |
            Время отправки кампании в формате RFC3339. Используется UTC.
          example: "2024-04-20T10:00:00Z"
        recipients:
          type: array
          description: Список email-адресов получателей кампании.
          minItems: 1
          items:
            type: string
            format: email
      description: Параметры создаваемой кампании.
    CreateCampaignResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
          description: Идентификатор созданной кампании.
      required:
        - id
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Сообщение об ошибке.
      required:
        - error
    CampaignStats:
      type: object
      properties:
        total:
          type: integer
          format: int32
          description: Всего сообщений в кампании.
        pending:
          type: integer
          format: int32
          description: Сообщений в очереди.
        sent:
          type: integer
          format: int32
          description: Успешно отправленных сообщений.
        failed:
          type: integer
          format: int32
          description: Сообщений с ошибкой доставки.
      required:
        - total
        - pending
        - sent
        - failed
    CampaignListItem:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        scheduled_at:
          type: string
          format: date-time
        status:
          type: string
        created_at:
          type: string
          format: date-time
        stats:
          $ref: '#/components/schemas/CampaignStats'
      required:
        - id
        - name
        - scheduled_at
        - status
        - created_at
        - stats
    CampaignDetails:
      allOf:
        - $ref: '#/components/schemas/CampaignListItem'
        - type: object
          properties:
            body:
              type: string
          required:
            - body
  examples:
    WeeklyNewsletter:
      summary: Еженедельная рассылка новостей
      description: Подходит для отправки регулярных дайджестов.
      value:
        name: Weekly Newsletter #42
        body: |
          <h1>Новости недели</h1>
          <p>Привет, {{name}}!</p>
          <ul>
            <li>Обновления продукта</li>
            <li>Предстоящие мероприятия</li>
            <li>Статьи блога</li>
          </ul>
        scheduled_at: 2024-04-20T10:00:00Z
        recipients:
          - alex@example.com
          - maria@example.com
          - ivan@example.com
    ProductLaunch:
      summary: Запуск нового продукта
      description: Используйте, чтобы анонсировать крупные релизы.
      value:
        name: New Feature Launch
        body: |
          <h1>Запуск функции "Быстрые ответы"</h1>
          <p>Расскажите клиентам, как использовать новую функцию.</p>
          <p>Добавьте CTA на регистрацию демо.</p>
        scheduled_at: 2024-05-01T08:30:00Z
        recipients:
          - founders@partner.io
          - marketing@client.co
    Reactivation:
      summary: Реактивация неактивных пользователей
      description: Шаблон для кампаний возврата пользователей.
      value:
        name: We Miss You
        body: |
          <h1>Мы соскучились!</h1>
          <p>Дарим промокод RETURN20 для вашего следующего заказа.</p>
          <p>Укажите дедлайн, чтобы стимулировать действие.</p>
        scheduled_at: 2024-04-15T12:00:00Z
        recipients:
          - inactive.customer1@example.com
          - inactive.customer2@example.com
          - inactive.customer3@example.com